# Copyright 2017 ThoughtWorks, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

###############################################################################################
# This file is autogenerated by the repository at https://github.com/gocd/docker-gocd-agent.
# Please file any issues or PRs at https://github.com/gocd/docker-gocd-agent
###############################################################################################

FROM debian:8
MAINTAINER GoCD <go-cd-dev@googlegroups.com>

LABEL gocd.version="17.6.0" \
  description="GoCD agent based on debian version 8" \
  maintainer="GoCD <go-cd-dev@googlegroups.com>" \
  gocd.full.version="17.6.0-5142" \
  gocd.git.sha="be1ff52e07d80323fcc615864a64f3afe83b7016"

ADD "https://download.gocd.org/binaries/17.6.0-5142/generic/go-agent-17.6.0-5142.zip" /tmp/go-agent.zip
ADD https://github.com/krallin/tini/releases/download/v0.14.0/tini-static-amd64 /usr/local/sbin/tini
ADD https://github.com/tianon/gosu/releases/download/1.10/gosu-amd64 /usr/local/sbin/gosu

# allow mounting ssh keys, dotfiles, and the go server config and data
VOLUME /godata

# force encoding
ENV LANG=en_US.utf8

RUN \
# add mode and permissions for files we added above
  chmod 0755 /usr/local/sbin/tini && \
  chown root:root /usr/local/sbin/tini && \
  chmod 0755 /usr/local/sbin/gosu && \
  chown root:root /usr/local/sbin/gosu && \
# add our user and group first to make sure their IDs get assigned consistently,
# regardless of whatever dependencies get added
  groupadd -g 1000 go && \
  useradd -u 1000 -g go -d /home/go -m go && \
  echo 'deb http://deb.debian.org/debian jessie-backports main' > /etc/apt/sources.list.d/jessie-backports.list && \
  apt-get update && \
  apt-get install -y openjdk-8-jre-headless ca-certificates-java="20161107~bpo8+1" git subversion mercurial openssh-client bash unzip && \
  apt-get autoclean && \
  /var/lib/dpkg/info/ca-certificates-java.postinst configure && \
# unzip the zip file into /go-agent, after stripping the first path prefix
  unzip /tmp/go-agent.zip -d / && \
  mv go-agent-17.6.0 /go-agent && \
  rm /tmp/go-agent.zip

  # install docker (based on https://github.com/docker-library/docker/blob/587b66d54a69996fc765c9671eb9bc8740172f2d/17.04/Dockerfile)

  RUN apt-get update \
      && apt-get install -y --no-install-recommends \
    		ca-certificates \
    		curl \
    		openssl \
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

  ENV DOCKER_BUCKET get.docker.com
  ENV DOCKER_VERSION 17.04.0-ce
  ENV DOCKER_SHA256 c52cff62c4368a978b52e3d03819054d87bcd00d15514934ce2e0e09b99dd100

  RUN set -x \
    && curl -fSL "https://${DOCKER_BUCKET}/builds/Linux/x86_64/docker-${DOCKER_VERSION}.tgz" -o docker.tgz \
    && echo "${DOCKER_SHA256} *docker.tgz" | sha256sum -c - \
    && tar -xzvf docker.tgz \
    && mv docker/* /usr/local/bin/ \
    && rmdir docker \
    && rm docker.tgz \
    && docker -v

  # install docker-in-docker (based on https://github.com/docker-library/docker/blob/587b66d54a69996fc765c9671eb9bc8740172f2d/17.04/dind/Dockerfile)

  RUN apt-get update \
      && apt-get install -y --no-install-recommends \
    		btrfs-progs \
    		e2fsprogs \
    		iptables \
    		xfsprogs \
    		xz-utils \
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

  # set up subuid/subgid so that "--userns-remap=default" works out-of-the-box
  RUN set -x \
    && groupadd -r dockremap \
    && useradd -r -g dockremap dockremap \
    && echo 'dockremap:165536:65536' >> /etc/subuid \
    && echo 'dockremap:165536:65536' >> /etc/subgid

  ENV DIND_COMMIT 3b5fac462d21ca164b3778647420016315289034

  RUN curl -fSL "https://raw.githubusercontent.com/docker/docker/${DIND_COMMIT}/hack/dind" -o /usr/local/bin/dind \
    && chmod +x /usr/local/bin/dind


  # runtime environment variables
  ENV AGENT_BOOTSTRAPPER_ARGS="-sslVerificationMode NONE" \
      AGENT_ENVIRONMENTS="" \
      AGENT_HOSTNAME="" \
      AGENT_KEY="" \
      AGENT_MAX_MEM=256m \
      AGENT_MEM=128m \
      AGENT_RESOURCES="" \
      GO_SERVER_URL="https://localhost:8154/go" \
      STORAGE_DRIVER="overlay2" \
      HOME="/var/go"






ADD docker-entrypoint.sh /

ENTRYPOINT ["/docker-entrypoint.sh"]
